### ISSUE TITLE
Typescript compile failure on npm start (loadable component)

### ISSUE THREAD

**Issue by wmossman** [hiroppy/ssr-sample#166]
@hiroppy 

This repo is a great starting point for loadable-components SSR with styled-components, typescript and webpack. I'd love to be able to run the app and see how it works but I'm running into an error on first `npm start`:

```> ssr-sample@1.0.0 start /Users/westonm/react-test/ssr-sample
> cross-env TS_NODE_FILES=true ts-node ./src/server/index.ts


/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/client/Router/Routes.ts:4:9 - error TS2322: Type 'Promise<ComponentClass<never, any> | FunctionComponent<never> | DefaultImportedComponent<never> | ConnectedComponentClass<ComponentClass<Props, any>, Pick<Props, "match" | "location" | "history" | "staticContext">>>' is not assignable to type 'Promise<DefaultComponent<Pick<Props, "match" | "location" | "history" | "staticContext">>>'.
  Type 'ComponentClass<never, any> | FunctionComponent<never> | DefaultImportedComponent<never> | ConnectedComponentClass<ComponentClass<Props, any>, Pick<Props, "match" | "location" | "history" | "staticContext">>' is not assignable to type 'DefaultComponent<Pick<Props, "match" | "location" | "history" | "staticContext">>'.
    Type 'ComponentClass<never, any>' is not assignable to type 'DefaultComponent<Pick<Props, "match" | "location" | "history" | "staticContext">>'.
      Type 'ComponentClass<never, any>' is not assignable to type 'ComponentClass<Pick<Props, "match" | "location" | "history" | "staticContext">, any>'.
        Types of property 'getDerivedStateFromProps' are incompatible.
          Type 'GetDerivedStateFromProps<never, any> | undefined' is not assignable to type 'GetDerivedStateFromProps<Pick<Props, "match" | "location" | "history" | "staticContext">, any> | undefined'.
            Type 'GetDerivedStateFromProps<never, any>' is not assignable to type 'GetDerivedStateFromProps<Pick<Props, "match" | "location" | "history" | "staticContext">, any>'.
              Types of parameters 'nextProps' and 'nextProps' are incompatible.
                Type 'Readonly<Pick<Props, "match" | "location" | "history" | "staticContext">>' is not assignable to type 'never'.

4   () => import(/* webpackChunkName: "Orgs" */ '../containers/Orgs').then(({ Orgs }) => Orgs),
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/loadable-components/types/index.d.ts:8:17
    8   getComponent: () => Promise<loadable.DefaultComponent<T>>,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
src/client/Router/Routes.ts:11:9 - error TS2322: Type 'Promise<ComponentClass<never, any> | FunctionComponent<never> | DefaultImportedComponent<never> | ConnectedComponentClass<ComponentClass<Props, any>, Pick<Props, never>>>' is not assignable to type 'Promise<DefaultComponent<Pick<Props, never>>>'.
  Type 'ComponentClass<never, any> | FunctionComponent<never> | DefaultImportedComponent<never> | ConnectedComponentClass<ComponentClass<Props, any>, Pick<Props, never>>' is not assignable to type 'DefaultComponent<Pick<Props, never>>'.
    Type 'ComponentClass<never, any>' is not assignable to type 'DefaultComponent<Pick<Props, never>>'.
      Type 'ComponentClass<never, any>' is not assignable to type 'ComponentClass<Pick<Props, never>, any>'.
        Types of property 'getDerivedStateFromProps' are incompatible.
          Type 'GetDerivedStateFromProps<never, any> | undefined' is not assignable to type 'GetDerivedStateFromProps<Pick<Props, never>, any> | undefined'.
            Type 'GetDerivedStateFromProps<never, any>' is not assignable to type 'GetDerivedStateFromProps<Pick<Props, never>, any>'.
              Types of parameters 'nextProps' and 'nextProps' are incompatible.
                Type 'Readonly<Pick<Props, never>>' is not assignable to type 'never'.

11   () => import(/* webpackChunkName: "Top" */ '../containers/Top').then(({ Top }) => Top),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/loadable-components/types/index.d.ts:8:17
    8   getComponent: () => Promise<loadable.DefaultComponent<T>>,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
src/client/Router/Routes.ts:19:5 - error TS2322: Type 'Promise<ComponentClass<never, any> | FunctionComponent<never> | DefaultImportedComponent<never> | ConnectedComponentClass<typeof NotFound, Pick<Props, never>>>' is not assignable to type 'Promise<DefaultComponent<Pick<Props, never>>>'.
  Type 'ComponentClass<never, any> | FunctionComponent<never> | DefaultImportedComponent<never> | ConnectedComponentClass<typeof NotFound, Pick<Props, never>>' is not assignable to type 'DefaultComponent<Pick<Props, never>>'.
    Type 'ComponentClass<never, any>' is not assignable to type 'DefaultComponent<Pick<Props, never>>'.
      Type 'ComponentClass<never, any>' is not assignable to type 'ComponentClass<Pick<Props, never>, any>'.
        Types of property 'getDerivedStateFromProps' are incompatible.
          Type 'GetDerivedStateFromProps<never, any> | undefined' is not assignable to type 'GetDerivedStateFromProps<Pick<Props, never>, any> | undefined'.
            Type 'GetDerivedStateFromProps<never, any>' is not assignable to type 'GetDerivedStateFromProps<Pick<Props, never>, any>'.
              Types of parameters 'nextProps' and 'nextProps' are incompatible.
                Type 'Readonly<Pick<Props, never>>' is not assignable to type 'never'.

19     import(/* webpackChunkName: "404", webpackPrefetch: true */ '../containers/NotFound').then(
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20       ({ NotFound }) => NotFound
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21     ),
   ~~~~~

  node_modules/loadable-components/types/index.d.ts:8:17
    8   getComponent: () => Promise<loadable.DefaultComponent<T>>,
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.

    at createTSError (/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:245:12)
    at reportTSError (/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:249:19)
    at getOutput (/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:362:34)
    at Object.compile (/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:395:32)
    at Module.m._compile (/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:473:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/westonm/react-test/ssr-sample/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssr-sample@1.0.0 start: `cross-env TS_NODE_FILES=true ts-node ./src/server/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssr-sample@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/westonm/.npm/_logs/2019-07-25T23_03_59_726Z-debug.log
```

I didn't make any changes to the code before running `npm i` and `npm start`

**Comment by hiroppy** [comment]
fm, I'll check this issue. Currently, INFO: I've been updating loadable-components. https://github.com/hiroppy/ssr-sample/pull/150

**Comment by hiroppy** [comment]
I fixed this problem, thanks

**Comment by 77xi** [comment]
> I fixed this problem, thanks

still throw err at branch of `master` and `feature/loadble`

**Comment by hiroppy** [comment]
Yes, I must fix many problems...
